fnfweb_4.6.14/fnfweb/src/java/org/ipvision/sms/SMSAction.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ipvision.sms;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import org.ipvision.communication.MainBean;
import org.ipvision.net.OnReceiveListner;
import org.ipvision.users.LoggedUserProfile;
import org.ipvision.utils.ServerConstants;
import org.richfaces.json.JSONObject;

/**
 *
 * @author user
 */
@ManagedBean(name = "smsAction")
@SessionScoped
public class SMSAction implements OnReceiveListner, Serializable {

//  AullAuthontication System
    @ManagedProperty(value = "#{mainBean}")
    private MainBean mainBean;
//  End
    @ManagedProperty(value = "#{loggedUserProfile}")
    private LoggedUserProfile loggedUserProfile;
    private String mbl;
    private String mg;
    boolean isComplete = false;
    private String errorMessage;
    private String friendName;
    private String grpId;
    private boolean actionDisable = false;

    public SMSAction() {
    }

    public void sendSMS() {
//        System.out.println("sendSMS");
        actionDisable = true;
        try {
            String rendom = ServerConstants.getRandromPacketId();
            String key = loggedUserProfile.getUserIdentity() + rendom;
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("actn", ServerConstants.TYPE_FRIEND_SMS);
             jsonObject.put("sId", loggedUserProfile.getSessionId());
            jsonObject.put("mg", loggedUserProfile.getUserIdentity() + "," + rendom + "," + mbl + "," + mg);
            System.out.println("sendSMS::" + jsonObject.toString());

//            JSONObject jsonObject = new JSONObject();
//            jsonObject.put("actn", ServerConstants.UPDATE);
//            jsonObject.put("type", ServerConstants.SEND_SMS);
//            jsonObject.put("pckId", key);
//            jsonObject.put("sId", loggedUserProfile.getSessionId());
//            jsonObject.put("mbl", mbl);
//            jsonObject.put("uId", loggedUserProfile.getUserIdentity());
//            jsonObject.put("full_name", "24FnF");
//            jsonObject.put("mg", mg);
//            System.out.println("sendSMS::" + jsonObject.toString());
            mainBean.getServerCommunication().sendSMSPacket(jsonObject.toString(), key);
            while (true) {
                try {
                    Thread.sleep(100);
                    if (isComplete) {
                        isComplete = false;
                        break;
                    } else {
                        if (errorMessage == null || errorMessage.length() <= 0) {
                            continue;
                        } else {
                            break;
                        }
                    }
                } catch (InterruptedException ex) {
                }
            }
        } catch (Exception e) {
        }
    }

    @Override
    public void onReceivedMessage(String msg) {
//        int actn = 0;
//        String sentPhoneNumbers[];
//        String failedPhoneNumbers[];
//        int sent = 0;
//        int failed = 0;
        try {
            JSONObject jsonObject = new JSONObject(msg);
            System.out.println("Received::" + msg);
            int actn = jsonObject.getInt("actn");
            if (actn == ServerConstants.TYPE_FRIEND_SMS) {
                if (jsonObject.has("sCode")) {
                    int statusCode = jsonObject.getInt("sCode");
                    switch (statusCode) {
                        case ServerConstants.STATUS_IN_PROGRESS:
                            errorMessage = "Processed";
                            break;
                        case ServerConstants.STATUS_NOT_DELEVERED:
                            errorMessage = "Message Not Develived";
                            break;
                        case ServerConstants.STATUS_NOT_ENOUGH_BALANCE:
                            errorMessage = "Sorry! You have not enough balance!";
                            break;
                        case ServerConstants.STATUS_SENT:
                            errorMessage = "Message sent successfuly.";
                            break;
                    }
                }
                System.out.println("Received::" + errorMessage);
                isComplete=true;
            }

//            if (actn == ServerConstants.TYPE_SEND_SMS) {
//                if (jsonObject.has("report")) {
//                    JSONArray jsonArray = jsonObject.getJSONArray("report");
//                    sentPhoneNumbers = new String[jsonArray.length()];
//                    failedPhoneNumbers = new String[jsonArray.length()];
//
//                    for (int i = 0; i < jsonArray.length(); i++) {
//                        JSONObject inerObject = new JSONObject();
//                        inerObject = (JSONObject) jsonArray.get(i);
//                        if (inerObject.getBoolean("sucs")) {
//                            sentPhoneNumbers[sent++] = inerObject.getString("mbl");
//                        } else {
//                            failedPhoneNumbers[failed++] = inerObject.getString("mbl");
//                        }
//                    }
//                    String notifyString = "";
//                    if (sent > 0) {
//                        notifyString = "mg sent to:";
//                        for (int i = 0; i < sent; i++) {
//                            notifyString = notifyString.concat(sentPhoneNumbers[i]);
//                            if (i + 1 != sent) {
//                                notifyString = notifyString.concat(",");
//                            }
//                        }
//                        notifyString = notifyString.concat("\n");
//                    }
//                    if (failed > 0) {
//                        notifyString = notifyString.concat("cannot send to:");
//                        for (int i = 0; i < failed; i++) {
//                            if (i != 0) {
//                                notifyString = notifyString.concat(",");
//                            }
//                            notifyString = notifyString.concat(failedPhoneNumbers[i]);
//
//                        }
//                    }
//                    errorMessage = notifyString;
//                    isComplete = true;
//                } else if (jsonObject.has("sucs")) {
//                    if (jsonObject.getBoolean("sucs")) {
//                        //
//                    } else {
//                        if (jsonObject.has("mg")) {
//                            errorMessage = jsonObject.getString("mg");
//                            isComplete = true;
//                        } else {
//                            isComplete = true;
//                            errorMessage = "Invalid Session";
//                        }
//                    }
//                }
//            }
        } catch (Exception e) {
        }
    }

    public MainBean getMainBean() {
        return mainBean;
    }

    public void setMainBean(MainBean mainBean) {
        this.mainBean = mainBean;
    }

    public LoggedUserProfile getLoggedUserProfile() {
        return loggedUserProfile;
    }

    public void setLoggedUserProfile(LoggedUserProfile loggedUserProfile) {
        this.loggedUserProfile = loggedUserProfile;
    }

    public String getMobilePhone() {
        return mbl;
    }

    public void setMobilePhone(String mbl) {
        this.mbl = mbl;
    }

    public String getMessage() {
        return mg;
    }

    public void setMessage(String mg) {
        this.mg = mg;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    public String getFriendName() {
        return friendName;
    }

    public void setFriendName(String friendName) {
        this.friendName = friendName;
    }

    public String getGroupId() {
        return grpId;
    }

    public void setGroupId(String grpId) {
        this.grpId = grpId;
    }

    public boolean isActionDisable() {
        return actionDisable;
    }

    public void setActionDisable(boolean actionDisable) {
        this.actionDisable = actionDisable;
    }
}

fnfweb_4.6.14/fnfweb/web/secure/chat/chat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
    <ui:composition template="/secure/user/user_template.xhtml" xmlns:a4j="http://richfaces.org/a4j"
                    xmlns:rich="http://richfaces.org/rich">
        <ui:define name="userdetails">
            
            <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/scripts/chat/chat.js" />
            <div style="color:#0000FF;font-weight:bold; "><h:outputText  value="#{userHomeAction.setProfile(param['friend'])}"/></div>
            <ui:param name="userProfile" value="#{userHomeAction.userProfile}" />
            <ui:param name="loggedProfile" value="#{loggedUserProfile}" />
            <ui:param name="isFriend" value="#{friendsBean.isMyFriend(userProfile.userIdentity)}" />
            <h:panelGroup rendered="#{isFriend}">
                <div style="font-size: 15px;font-weight: bold;padding-left: 10px">
                    <div style="float:left">
                        #{userProfile.firstName} &nbsp;#{userProfile.lastName}
                    </div>
                    <div style="float:left;margin-left:50px;">
                        <a href="javascript:void(0)" onclick="javascript:showChatWindow('#{userProfile.userIdentity}')" >IM Window</a>
                    </div>
                    <div style="clear:both"></div>
                    #{chatWindowActivity.setFriendName(userProfile.userIdentity)}
                </div>
                <div style="padding:10px 0;margin:10px 0;">
                    <h:form>
                        <h:selectOneMenu class="jnumDays editbox3" id="historyOption" value="#{chatWindowActivity.numDays}">
                            <f:selectItem itemValue="#{null}" itemLabel="History..." />
                            <f:selectItem itemLabel="Yesterday" itemValue="1"/>
                            <f:selectItem itemLabel="Last 7 Days" itemValue="7"/>
                            <f:selectItem itemLabel="Last 1 Month" itemValue="30"/>
                            <f:selectItem itemLabel="Last 3 Months" itemValue="90"/>
                        </h:selectOneMenu>
                        <input type="button" class="submit_button jfriendHistory"  value="History" />
                    </h:form>
                    <h:form class="messagePanel" style="min-height:300px;">
                        <script type="text/javascript">scrollDown()</script>
                        <h:dataTable width="100%" var="con" value="#{chatWindowActivity.getFriendMessageList(userProfile.userIdentity) }">
                            <h:column>
                                <div style="float:left;width:80%;">
                                    <span class="cname"><h:outputLabel value="#{con.userName} : " /></span> <h:outputText escape="false" value="#{con.message}" />
                                </div>
                                <div style="clear:both"></div>
                                <div class="cdate">Sent at #{con.messageDateString}</div>
                            </h:column>
                        </h:dataTable>
                        <div class="chatPanel"></div>
                    </h:form>
                    <form id="messageForm">
                        <div class="sendingStatus" />
                        <input type="text" name="message" value="" size="50" class="jmessage" />
                        <input type="hidden" name="friendName" value="#{chatWindowActivity.friendName}" />
                        <input type="hidden" name="userName" value="#{loggedProfile.userIdentity}" />
                        <img id="emoticonBtn" src="#{facesContext.externalContext.requestContextPath}/resources/img/smile_icon.png" alt="Click to select Smiley"/>
                        <input type="submit" name="send" value="Send" class="jSendBtn" />
                    </form>

                    <div id="emoticons_changed">
                        <div class="jtab">
                            <ul >
                                <li class="tab_nav tab_nav_1"><div>Emoticon</div></li>
                                <li class="tab_nav tab_nav_2"><div>Sticker</div></li>
                            </ul>
                            <ul>
                                <li class="tab_body tab_body_1">
                                    <h:outputText escape="false" value="#{chatWindowActivity.getEmoticonList()}" />
                                </li>
                                <li class="tab_body tab_body_2">
                                    <h:outputText escape="false" value="#{chatWindowActivity.getStickerList()}" />
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </h:panelGroup>
            <h:panelGroup rendered="#{!isFriend}">
                <div>Sorry! Currently you are not confirmed friend yet. Please try later.</div>
            </h:panelGroup>
        </ui:define>
    </ui:composition>
</html>

fnfweb_4.6.14/fnfweb/web/secure/chat/friend_chat_window.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
    <h:head>
        #{chatWindowView.setUserProfile(param['friend'])}
        <link href="#{facesContext.externalContext.requestContextPath}/resources/img/favicon.ico" type="image/x-icon" rel="icon"></link>
        <title>#{chatWindowView.userProfile.firstName} &nbsp;#{chatWindowView.userProfile.lastName}</title>
        <style type="text/css">
            .submit_button {
                border:1px solid #057eb5; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;font-family:verdana, sans-serif; 
                padding: 3px 15px; text-shadow: 1px 1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; background-color: #07A4EB;
                background-image: -webkit-gradient(linear, left top, left bottom, from(#07A4EB), to(#0681B9));
                background-image: -webkit-linear-gradient(top, #07A4EB, #0681B9);
                background-image: -moz-linear-gradient(top, #07A4EB, #0681B9);
                background-image: -ms-linear-gradient(top, #07A4EB, #0681B9);
                background-image: -o-linear-gradient(top, #07A4EB, #0681B9);
                background-image: linear-gradient(to bottom, #07A4EB, #0681B9);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#07A4EB, endColorstr=#0681B9);
                margin:5px;
                cursor: pointer;
            }
            #emoticons_changed
            {
                display: none;
                border: 1px solid #666;
                background:#fff;
                position: absolute;
                left: -10000px;
                top: 0;
                max-width:310px;
                overflow: hidden;
            }
            #emoticons_changed table{margin:0;padding:0;}
            #emoticons_changed table td{vertical-align:middle;}
            #emoticons_changed table td div.small{padding:2px;border:1px solid #fefefe;height:25px;width: 25px;}
            #emoticons_changed table td div.sticker{padding:2px;border:1px solid #fefefe;height:80px;width: 80px;}
            #emoticons_changed table td div.small img{height:25px;width: 25px;cursor: pointer;}
            #emoticons_changed table td div.sticker img{height:80px;width: 80px;cursor: pointer;}
            #emoticons_changed table td div:hover{border:1px solid #333;}
            #emoticonBtn{cursor:pointer;}
            .cname{font-weight:bold;text-transform:capitalize;margin-right:5px;vertical-align:top;}
            .cdate{font-size:8pt;color:#808080;margin-top:2px;}
            .mind{font-size:9pt;color:#333333;padding:0;margin:0;}
            .msgNotification{color:#f00;font-weight:bold;font-size:8pt;position:relative;top: -5px;}

            .jtab{font-size:9pt;}
            .jtab ul{list-style:none;margin:0;padding:0;}
            .jtab .tab_nav{float:left;cursor:pointer;text-align:center;color:#344e66;}
            .jtab .tab_nav div{background:#e8eced;border-left:1px solid #cccccc;border-right:1px solid #cccccc; border-top:1px solid #cccccc;padding:2px 10px;}
            .jtab .sel div{background:#fff;color:#cc0104;}
            .jtab .tab_body{clear:both;border:1px solid #DDD;padding:5px;max-height:250px;overflow-y:scroll;}
            .jtab .tab_body_2,.tab_body_3,.tab_body_4,.tab_body_5{display:none;}
        </style>
        <script src="#{facesContext.externalContext.requestContextPath}/resources/js/jquery-1.4.2.min.js" type="text/javascript"></script>
       
        <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/scripts/chat/chat.js" />
    </h:head>
    <h:body>
        #{chatWindowView.setFriendName(chatWindowView.userProfile.userIdentity)}
        <ui:param name="userProfile" value="#{chatWindowView.userProfile}" />
        <ui:param name="loggedProfile" value="#{loggedUserProfile}" />
        <div style="border:1px solid navy;padding:10px;margin:10px;">
            <div style="vertical-align:top">
                <img src="#{userProfile.profileImage}" alt="#{userProfile.firstName} &nbsp;#{userProfile.lastName}" style="margin-right:10px;float:left;" />
                <div style="float:left">
                    <span style="font-weight:bold;font-size:15pt;">#{userProfile.firstName} &nbsp;#{userProfile.lastName}</span>
                    <p class="mind">#{userProfile.whatisInYourMind}</p>
                </div>
                <div style="clear:both;" />
            </div>
            <div style="clear:both;" />
            <h:form class="messagePanel" style="min-height:400px;">
                <script type="text/javascript">scrollDown()</script>
                <div class="block">
                    <h:dataTable width="100%" var="con" value="#{chatWindowView.getFriendMessageList(userProfile.userIdentity)}">
                        <h:column>
                            <div style="float:left;width:80%;">
                                <span class="cname"><h:outputLabel value="#{con.userName} : " /></span> <h:outputText escape="false" value="#{con.message}" />
                            </div>
                            <div style="clear:both"></div>
                            <div class="cdate">Sent at #{con.messageDateString}</div>
                        </h:column>
                    </h:dataTable>
                    <div class="chatPanel"></div>
                </div>
            </h:form>

            <form id="messageForm">
                <div class="sendingStatus" />
                <input type="text" name="message" value="" size="50" class="jmessage" />
                <input type="hidden" name="friendName" value="#{chatWindowView.friendName}" />
                <input type="hidden" name="userName" value="#{loggedProfile.userIdentity}" />
                <img id="emoticonBtn" src="#{facesContext.externalContext.requestContextPath}/resources/img/smile_icon.png" alt="Click to select Smiley"/>
                <input type="submit" name="send" value="Send" class="jSendBtn" />
            </form>

            <div id="emoticons_changed">
                <div class="jtab">
                    <ul >
                        <li class="tab_nav tab_nav_1"><div>Emoticon</div></li>
                        <li class="tab_nav tab_nav_2"><div>Sticker</div></li>
                    </ul>
                    <ul>
                        <li class="tab_body tab_body_1">
                            <h:outputText escape="false" value="#{chatWindowActivity.getEmoticonList()}" />
                        </li>
                        <li class="tab_body tab_body_2">
                            <h:outputText escape="false" value="#{chatWindowActivity.getStickerList()}" />
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </h:body>
</html>

fnfweb_4.6.14/fnfweb/web/secure/chat/group_chat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
    <ui:composition template="/secure/user/user_template.xhtml" xmlns:a4j="http://richfaces.org/a4j"
                    xmlns:rich="http://richfaces.org/rich">
        <ui:define name="userdetails">
           
            <script type="text/javascript" src="#{facesContext.externalContext.requestContextPath}/scripts/chat/chat.js" />
            <div class="topheadline">Group Chat</div>
            <div style="color:#0000FF;font-weight:bold; ">#{groupChatWindow.setGroupDetails(param['groupId'])}</div>
            <div style="border: 1px solid #ededed;font-size: 15px;font-weight:bold;padding:10px;margin-top: 5px">
                Group Name:  <h:outputText  value="#{groupChatWindow.groupDetails.groupName}"/>
            </div>
            #{groupChatWindow.setFriendName(groupChatWindow.groupDetails.groupMembers)}
            #{groupChatWindow.setGroupId(groupChatWindow.groupDetails.groupId)}
            <div style="padding:10px 0;margin:10px 0;">
                <h:form id="historyPanel">
                    <h:selectOneMenu class="editbox3 jnumDays" id="historyOption" value="#{groupChatWindow.numDays}">
                        <f:selectItem itemValue="#{null}" itemLabel="History..." />
                        <f:selectItem itemLabel="Yesterday" itemValue="1"/>
                        <f:selectItem itemLabel="Last 7 Days" itemValue="7"/>
                        <f:selectItem itemLabel="Last 1 Month" itemValue="30"/>
                        <f:selectItem itemLabel="Last 3 Months" itemValue="90"/>
                    </h:selectOneMenu>
                    <h:inputHidden value="#{groupChatWindow.groupId}"></h:inputHidden>
                    <input type="button" name="history" value="History" class="submit_button jgroupHistory" />
                </h:form>
                <h:form class="messagePanel" style="min-height:300px;">
                    <script type="text/javascript">scrollDown()</script>
                    <h:dataTable style="width:100%;" var="con" value="#{groupChatWindow.getGroupMessageList(groupChatWindow.groupDetails.groupId)}">
                        <h:column>
                            <div style="float:left;width:80%;">
                                <span class="cname"><h:outputLabel value="#{con.userName} : " /></span> <h:outputText escape="false" value="#{con.message}" />
                            </div>
                            <div style="clear:both"></div>
                            <div class="cdate">Sent at #{con.messageDateString}</div>
                        </h:column>
                    </h:dataTable>
                    <div class="chatGroupPanel"></div>
                </h:form>
                <form id="groupMessageForm">
                    <div id="sendingStatus" />
                    <input type="text" id="message" name="message" value="" class="jmessage" size="50" />
                    <input type="hidden" name="friendName" value="#{groupChatWindow.friendName}" />
                    <input type="hidden" name="userName" value="#{loggedUserProfile.userIdentity}" />
                    <input type="hidden" name="groupId" value="#{groupChatWindow.groupId}" />
                    <img id="emoticonBtn" src="#{facesContext.externalContext.requestContextPath}/resources/img/smile_icon.png" alt="Click to select Smiley"/>
                    <input type="submit" name="send" value="Send" class="submit_button" />
                </form>
                <div id="emoticons_changed">
                    <div class="jtab">
                        <ul >
                            <li class="tab_nav tab_nav_1"><div>Emoticon</div></li>
                            <li class="tab_nav tab_nav_2"><div>Sticker</div></li>
                        </ul>
                        <ul>
                            <li class="tab_body tab_body_1">
                                <h:outputText escape="false" value="#{chatWindowActivity.getEmoticonList()}" />
                            </li>
                            <li class="tab_body tab_body_2">
                                <h:outputText escape="false" value="#{chatWindowActivity.getStickerList()}" />
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </ui:define>
    </ui:composition>
</html>